# Generated by Django 3.2.6 on 2021-09-02 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payloadnumber', models.IntegerField()),
                ('content', models.TextField(default=None)),
                ('programName', models.CharField(choices=[('french', 'French'), ('spanish', 'Spanish'), ('none', 'None')], default='none', max_length=40)),
            ],
            options={
                'ordering': ['programName', 'payloadnumber'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programName', models.CharField(choices=[('french', 'French'), ('spanish', 'Spanish')], default='spanish', max_length=40)),
                ('programCount', models.IntegerField(default=0)),
                ('firstname', models.CharField(default='', max_length=40)),
                ('lastname', models.CharField(default='', max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('startTime', models.TimeField(default=django.utils.timezone.now)),
                ('endTime', models.TimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
                ('served', models.BooleanField(default=False)),
                ('totalCount', models.IntegerField(default=0)),
                ('totalComplete', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textresponse', models.TextField(default=None, max_length=1000, verbose_name='Your Translation')),
                ('finished', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reponses', to='reTranslation.payload')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='reTranslation.program')),
            ],
            options={
                'ordering': ['payload__payloadnumber'],
            },
        ),
    ]
