# Generated by Django 3.2.6 on 2021-09-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reTranslation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='programs/')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProgramPhoto', to='reTranslation.program')),
            ],
        ),
    ]
