# Generated by Django 3.2.6 on 2021-09-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reTranslation', '0003_auto_20210902_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='isthisblack',
            field=models.BooleanField(default=False),
        ),
    ]
