# Generated by Django 3.2.6 on 2021-09-10 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reTranslation', '0004_program_isthisblack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='isthisblack',
        ),
    ]
