# Generated by Django 3.2.6 on 2021-08-27 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reTranslation', '0004_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payload',
            name='payloadpath',
        ),
        migrations.RemoveField(
            model_name='payload',
            name='program',
        ),
        migrations.AddField(
            model_name='payload',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='payload',
            name='programName',
            field=models.CharField(choices=[('french', 'French'), ('spanish', 'Spanish'), ('none', 'None')], default='none', max_length=40),
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textresponse', models.TextField(default=None, max_length=1000)),
                ('payload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reponses', to='reTranslation.payload')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='reTranslation.programs')),
            ],
        ),
    ]
