# Generated by Django 3.2.6 on 2021-08-27 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reTranslation', '0005_auto_20210827_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programs',
            new_name='Program',
        ),
    ]
