# Generated by Django 3.2.6 on 2021-10-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reTranslation', '0005_remove_program_isthisblack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='textresponse',
            field=models.TextField(default=None, max_length=100000, verbose_name='Your Translation'),
        ),
    ]
