# Generated by Django 3.2.6 on 2022-01-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reTranslation', '0006_alter_reponse_textresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='programName',
            field=models.CharField(choices=[('french', 'French'), ('spanish', 'Spanish'), ('portuguese', 'Portuguese'), ('none', 'None')], default='none', max_length=40),
        ),
        migrations.AlterField(
            model_name='program',
            name='programName',
            field=models.CharField(choices=[('french', 'French'), ('spanish', 'Spanish'), ('portuguese', 'Portuguese')], default='spanish', max_length=40),
        ),
    ]
