# Generated by Django 3.2.6 on 2021-08-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reTranslation', '0006_rename_programs_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payload',
            options={'ordering': ['programName', 'payloadnumber']},
        ),
        migrations.AddField(
            model_name='program',
            name='firstname',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='program',
            name='lastname',
            field=models.CharField(default='', max_length=40),
        ),
    ]
